spring:
  application:
    name: films
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/filmsRating
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true